backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: "sermons"
    label: "Sermons"
    folder: "content/sermons"
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {
          lavel: "Template Path",
          name: templatePath,
          widget: hidden,
          default: "sermon-template.js",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/markdown-pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "About Text", name: "about", widget: markdown }
          - { label: "News Headline", name: "newsHeadline", widget: string }
          - { label: "News Body", name: "newsBody", widget: markdown }
      - file: "src/markdown-pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "About Title", name: "aboutTitle", widget: string }
          - { label: "About Text", name: "about", widget: markdown }
          - { label: "Mission Title", name: "missionTitle", widget: string }
          - { label: "Mission Text", name: "mission", widget: markdown }
          - { label: "Message Title", name: "messageTitle", widget: string }
          - { label: "Message Text", name: "message", widget: markdown }
          - { label: "We Believe Title", name: "believeTitle", widget: string }
          - { label: "We Believe Text", name: "believe", widget: markdown }
      - file: "src/markdown-pages/stephenministry.md"
        label: "Stephen Ministry"
        name: "stephenministry"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "About Title", name: "aboutTitle", widget: string }
          - { label: "About Text", name: "about", widget: markdown }
          - { label: "Contact Title", name: "contactTitle", widget: string }
          - { label: "Contact Text", name: "contact", widget: markdown }
      - file: "src/markdown-pages/newsletter.md"
        label: "Newsletter"
        name: "newsletter"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "newsletter-page",
            }
          - { label: "Newsletter", name: "newsletter", widget: file }
